### PR TITLE
fix: updated configuration for clustered env

### PR DESCRIPTION
**Pull request by bitchecker**
Loading the right configuration on clustered environment in order to provide Load Balancing and Failover.

This solves https://github.com/Clivern/Lynx/issues/137

### CODE REVIEW

**Comment by Clivern** [comment]
Hi @bitchecker,

Can you please update the docs too, I am fine with merging it

the following should be adjusted in 
https://github.com/Clivern/Lynx/blob/main/docs/_documentation/Installation.md?plain=1#L99-L100
https://github.com/Clivern/Lynx/blob/main/README.md?plain=1#L79-L80

```
wget https://raw.githubusercontent.com/Clivern/Lynx/main/nginx-cluster.conf \
    -O nginx.conf
// Should be
wget https://raw.githubusercontent.com/Clivern/Lynx/main/nginx-cluster.conf \
    -O nginx-cluster.conf
```

**Comment by bitchecker** [comment]
> ```
> wget https://raw.githubusercontent.com/Clivern/Lynx/main/nginx-cluster.conf \
>     -O nginx.conf
> // Should be
> wget https://raw.githubusercontent.com/Clivern/Lynx/main/nginx-cluster.conf \
>     -O nginx-cluster.conf
> ```

I think that this is correct!
The default config name for nginx is `nginx.conf` so the name that you use for it is right, in fact, in the [PR](https://github.com/Clivern/Lynx/pull/138/files) I'm just updating the config file, but the destination name remains the same.

**Comment by Clivern** [comment]
What i meant is that the docs guide users to setup a cluster using these two commands, cloning the whole project is not even required.

'''
$ wget https://raw.githubusercontent.com/Clivern/Lynx/main/docker-compose-cluster.yml \
    -O docker-compose.yml
$ wget https://raw.githubusercontent.com/Clivern/Lynx/main/nginx-cluster.conf \
    -O nginx.conf

$ docker-compose up -d
'''

So if i merge your PR, these two commands won't work. Right? you try to mount a local nginx-cluster.conf file

**Comment by bitchecker** [comment]
Hi @Clivern,
Thanks for explanation! 

It's clear now because cloning the whole project is not even required!

I updated the code right now. 😃

**Comment by Clivern** [comment]
Thanks @bitchecker

**Pull request merged**
